/* data.js 的中文翻译版 — id/结构/links 保持一致，只翻译 label/story/text/title。 */

const DATA_ZH = {
  profile: {
    name: 'Paul Bhang',
    hangul: '方相勋',
    tagline: '15年 · 5大洲 · 4种语言',
    places: '杭州 · 首尔',
    hero1: '选一个词，',
    hero2: '看见我。',
    heroSub: '我脑海中漂浮的词语。<b>选一选，连一连。</b>',
    faces: '语言者 · 贸易人 · 匠人 · 教育者 · 讲故事的人 · 探索者',
    email: 'bikeryhz@hotmail.com',
    location: '中国杭州 · 韩国仁川',
    contentAsOf: '2026.07.17',
  },

  nodes: [
    { id: 'interp', label: '口译', type: 'core', status: 'told', fresh: true,
      story: '我从来不是专业口译员。只是很长时间里，作为兼职、作为工作的一部分，一直在做口译和翻译。这件事最难的不是语言，而是用我自己的嘴，说出别人的想法和话语。哪怕是我完全不认同的话、与我的想法截然相反的话，一旦用我的声音说出来，就感觉像是我自己说的。那时的我，既没有失去自己，也没能把它完全当作"只是工作"——我站在两者之间的某个地方。而正是那份不适成了动力：与其替别人说话，不如用外语说出我自己的话。',
      links: ['multiling', 'bridge', 'vienna', 'shanghai'] },
    { id: 'multiling', label: '多语言', type: 'core', status: 'told', fresh: true,
      story: '换一种语言，性格也会跟着换。说英语时，最自然的我会出现——没有敬语，西方文化就浸在这门语言里，说着说着人也会那样行动。这也是我最年少时学的语言，象征着自由，而且多是在自由的情境下使用的。同样的原因，说日语时我会变得过分小心，说中文时又会变得过分大胆。而韩语——虽然是我现在教的语言——却是我说起来最谨慎的语言：母语的分量、教师的身份、一种"我是否在使用一门承载着文化优越感的语言"的顾虑，还有那些只在懂韩语的人之间才起作用的微妙语感，可能会伤到别人的担忧。比起"哪种语言最像我"，更准确的问题是——在什么样的情境下，我更多地受哪种语言的影响。',
      links: ['interp', 'teaching', 'boundary', 'freedom'] },
    { id: 'sales', label: '销售', type: 'core', status: 'seed',
      story: '从盐到木材、店铺装置、再到汽车零件，我什么都卖过。卖的东西一直在变，但本质从未改变——弄清楚对方真正想要的是什么。',
      links: ['salt', 'timber', 'shanghai', 'trade'] },
    { id: 'pm', label: 'PM', type: 'core', status: 'told',
      story: '在管理北京现代项目时我明白了：技术问题的一半其实是文化问题。能居中调解的人才能救活一个项目。但作为庞大组织中的一颗螺丝钉工作着，一种遗憾也在心里滋长——我从没有从头到尾用自己的双手做出过什么。',
      links: ['shanghai', 'interp', 'hands', 'boundary'] },
    { id: 'subtitle', label: '字幕', type: 'core', status: 'seed',
      story: '六年间我制作韩英字幕。翻译的问题从来不只是语言，更是时机、节奏，以及画面容不下的言外之意。一行字幕能装下的，比想象中少得多。',
      links: ['subline', 'interp', 'hangzhou'] },
    { id: 'bike', label: '自行车', type: 'core', status: 'told',
      story: '三十二岁那年，我进了东京的自行车制作学校。亲手设计车架，按自己想的样子做出来。自行车对我来说是自由的象征——能去任何地方，敢于挑战新事物。那是最贴近我理想的一件物品。别人在积累履历的年纪，我在组装车轮，第一次完完全全做出了属于自己的东西。',
      links: ['tokyo', 'hands', 'freedom', 'chain'] },
    { id: 'logi', label: '物流', type: 'core', status: 'seed',
      story: '经手空运和海运货物，我和上百家合作公司打过交道。物流是一个信任本身就是基础设施的世界。一次失误，就能让地球另一端的某个人停下脚步。',
      links: ['vienna', 'trade', 'survival'] },
    { id: 'teaching', label: '教育', type: 'core', status: 'told', fresh: true,
      story: '现在我在杭州师范大学教韩语。我总是对学生说——语言不该被当作机械的翻译来学，而要在把握它的文化环境和语境中去学。说外语时性格会改变，也是其中之一。每个人说外语时性格都会变，只是程度不同而已。教语言不是教语法，而是打开一扇通往文化的门。',
      links: ['multiling', 'hangzhou', 'bridge'] },
    { id: 'english', label: '英语', type: 'core', status: 'told', fresh: true,
      story: '说英语时，最自然的我会出现。那是我最早学的语言，象征着自由，也是在真正自由的处境里用得最多的语言。没有敬语，西方文化浸在语言里——说着说着，人也会那样行动。',
      links: ['multiling', 'freedom', 'interp'] },
    { id: 'translate', label: '翻译', type: 'core', status: 'told', fresh: true,
      story: '口译和翻译我做了很久——兼职也好，工作的一部分也好。不是专业口译员，但搬运文字和话语教会了我如何在语言之间生活。字幕也是同一条线的延伸。',
      links: ['interp', 'subtitle', 'multiling'] },
    { id: 'mediation', label: '斡旋', type: 'core', status: 'told',
      story: '管理北京现代项目时我明白了：一半看似技术的问题，其实是文化问题。能在韩国和中国之间斡旋的人，救活了那个项目。',
      links: ['pm', 'shanghai', 'interp', 'boundary'] },
    { id: 'repair', label: '维修', type: 'core', status: 'told',
      story: '在东京造自行车，在杭州 Bikery 修客人的车。维修不只是让机器活下去——也是我用双手学会信任世界的方式。',
      links: ['bike', 'hands', 'bikery'] },

    { id: 'pakistan', label: '巴基斯坦', type: 'place', era: '1997–1998', status: 'told',
      story: '父亲作为海军军官被派驻巴基斯坦，十四岁的我因此在伊斯兰堡生活了下来。最初的冲击，是看到伊斯兰教如何彻彻底底塑造着人们生活的每一部分。在足以撼动整个价值观的巨大变化面前，我第一次用身体明白了：人终究会在其中适应下来——而这适应过程中萌生的无数想法，会彻底改变一个人生活的方式。',
      links: ['stranger', 'boundary', 'adapt', 'islam'] },
    { id: 'png', label: '巴新', type: 'place', era: '2009–2010', status: 'told', fresh: true,
      story: '在莫尔兹比港面对的生活，比巴基斯坦更极端。我住在木材厂区内，一间由从韩国运来机器的贸易集装箱改造成的房子里。夜晚一到，电就断了，工厂的灯也熄了，随之而来的是漫长漆黑的夜。收集些木屑生火，喝一两瓶当时相当贵的啤酒，抬头望着格外明亮的星星——那就是那里的一天。死亡就在工作场所旁边，疟疾也太过常见。就是在那片黑暗与星空下，我明白了：我一直深信不疑的"常识"，其实只不过是我成长的那个世界的规则罢了。',
      links: ['timber', 'survival', 'stranger', 'commonsense'] },
    { id: 'vienna', label: '维也纳', type: 'place', era: '2005–2007', status: 'told', fresh: true,
      story: '二十多岁时，我独自在维也纳机场建起了一个分公司。在陌生的城市里从零开始建立一家公司。在欧洲腹地，我是个异乡人，而这反倒成了我的武器。每逢周末，我只背一个背包，周五一下班就直接跳上巴士或火车。在韩国，陆路跨境是不可能的事，所以每次一觉醒来就到了另一个国家，那种感觉每次都像个小小的奇迹。就这样，我掠过东欧一个又一个角落——直到在布拉格丢了行李。',
      links: ['logi', 'stranger', 'boundary', 'prague', 'croatia'] },
    { id: 'prague', label: '布拉格', type: 'place', era: '2005–2007', status: 'told', fresh: true,
      story: '那是在开往维也纳的路上，捷克布拉格中央车站。我正给韩国打电话，旁边一个男人不停地推我，想卖给我一台数码相机之类的东西。语言不通，我打手势让他走开。反复几次后，通完电话时，一个行李箱不见了——是一伙人干的。车站里挤满了人，却没人帮忙，我来回跑了好几圈也没找到。去了警察局，但那时候还没有监控这种东西。那一刻，我第一次明白了什么叫求助无门。我拖着剩下的沉重行李，一屁股坐在车站旁的公园里，打开一罐在附近超市买的原产百威——那时候只有捷克和斯洛伐克才能喝到。在那艰难的一刻，那啤酒竟然出奇地好喝。钱和欧铁通票都在那个行李箱里。从那天起，我不得不尽量省着花。我暂时借住在一个去当兵的朋友家里，欧洲的冬天冷得刺骨，暖气也不给力。那段日子的每一天，几乎都是买最便宜的一瓶桌酒和一份烤肉卷（kebab），裹着被子在床上吃完就算过去了。丢东西之前，我几乎每个周末都在去不同的国家——那种自由和这个拮据的冬天之间的落差不小。可即便如此，那瓶酒和那份烤肉卷，若是在韩国，也会是种奢侈。那是一段贫穷与异国式丰盈同时并存的时光。',
      links: ['vienna', 'stranger', 'survival'] },
    { id: 'croatia', label: '克罗地亚', type: 'place', era: '2005–2007', status: 'told', fresh: true,
      story: '在维也纳生活期间的所有周末旅行中，这是记忆最清晰的一个。那时候韩国那档有名的节目还没去那里拍摄过，几乎没人听说过克罗地亚。我沿着海岸坐船，下船逛了逛码头边的小镇——房子与房子之间晾衣绳上挂着的雪白衣物，船只维修厂旁悠闲地窝着的猫，还有房屋外墙上残留的弹孔。我隐约知道那里打过仗，却没想到那些痕迹还留在那里。让我在意的不是悲伤，而是那种奇怪感——明亮的表情与那些痕迹并排存在。那个国家早已美丽地重建起来了。',
      links: ['vienna', 'nomad', 'stranger'] },
    { id: 'cambodia', label: '柬埔寨', type: 'place', era: '2013年前后', status: 'told', fresh: true,
      story: '在上海工作结束、回韩国之前，我去柬埔寨旅行了一趟。一个曾经辉煌的历史如今成了唯一收入来源的国家，街头随处能遇到身有残疾的人。在某个古迹，我无意中听到两个美国游客的对话——带着嘲讽意味的玩笑。他们大概以为柬埔寨人听不懂他们的话，或者即便听懂了也不在乎。我说的不是全体美国人，只是——一个国家的形象，最终往往由偶然遇到的少数几个人所左右。同样是"战争的痕迹"，在克罗地亚留下的是奇怪感，在这里留下的却是悲伤。',
      links: ['boundary', 'stranger', 'commonsense'] },
    { id: 'tokyo', label: '东京', type: 'place', era: '2014–2016', status: 'told', fresh: true,
      story: '决定去东京，并不是某个戏剧性的瞬间。在汽车公司做项目经理，其实是份很好的工作——薪水不错，待遇也好。可生活渐渐变得乏味，没有热情的日子一天天累积。三十岁那年，我总是忍不住想，现在不做一次大的改变，恐怕就晚了。于是我放下那份安稳，重新回到东京去做一名学生。',
      links: ['bike', 'hands', 'pm', 'drift'] },
    { id: 'shanghai', label: '上海', type: 'place', era: '2010–2013', status: 'seed',
      story: '在把店铺装置出口到欧洲之后，我成了一家汽车安全零件公司的项目经理。韩中商业文化之间的翻译者——那才是我真正的头衔。',
      links: ['sales', 'pm', 'interp'] },
    { id: 'hangzhou', label: '杭州', era: '2017–至今', type: 'place', status: 'seed',
      story: '开了民宿，做过字幕，现在在大学教书。一个长期漂泊的人第一次在此扎根的城市。仍在书写中的一章。',
      links: ['teaching', 'subtitle', 'guesthouse'] },
    { id: 'ireland', label: '爱尔兰', type: 'place', era: '约1996年', status: 'told', fresh: true,
      story: '初中二年级，我第一次出国。在英国、法国、香港短暂停留几日，最后抵达都柏林住了一个月。虽是首都，房子后面却有条山坡小径，那栋两层小楼里养着两只大狗。它们本在沙发边待着，随时会跑过来一起玩，散步时间一到又跟着出门——这个画面至今仍是最清晰的记忆。第一次出国的经历，留下的不是某个人而是两只狗，这倒也不坏。',
      links: ['pakistan', 'nomad', 'stranger'] },
    { id: 'jinhae', label: '镇海', type: 'place', era: '1983 · 2003–2005', status: 'told',
      story: '这是我生命开始的地方，后来也是我在海军服兵役时回到的地方。父亲是海军军官，我们全家因此住在镇海。但我其实并不是在镇海出生的——那时镇海没有妇产科医院，母亲跨到马山才生下了我。从一开始，我就是一个不完全属于任何一个地方的人。',
      links: ['boundary', 'masan', 'stranger'] },
    { id: 'masan', label: '马山', type: 'place', era: '1983', status: 'told',
      story: '户籍上的故乡，但我一天也没在那里生活过。那只是母亲因镇海没有妇产科医院而暂时前往、生下我的地方。出生的地方和生活的地方从一开始就错位——也许，那就是我人生的第一个隐喻。',
      links: ['jinhae', 'boundary', 'nomad'] },

    { id: 'nomad', label: '游牧', type: 'associative', status: 'seed',
      story: '我从未在一座城市久留——首尔、维也纳、莫尔兹比港、上海、东京、杭州。漂泊从来不是逃避，而是收集——每一次都拾起一种不同的生活方式。',
      links: ['drift', 'stranger', 'survival'] },
    { id: 'boundary', label: '边界', type: 'associative', status: 'told',
      story: '有人问起故乡，我通常会说自己是个没有故乡的人。出生地马山我从未住过，此后一生都在各国之间辗转。哪里都不算完全的里面，也不算完全的外面——是韩国人，却在中国教书；是销售员，也是修理工。有些东西，只有站在边界上的人才看得见。若要选一个最能描述我的词，大概就是这个。',
      links: ['stranger', 'bridge', 'nomad', 'masan'] },
    { id: 'stranger', label: '异乡', type: 'associative', status: 'seed',
      story: '我早已习惯以陌生人的身份生活。异乡人因为对什么都不理所当然，所以看到的更多。不适感，很久以前就成了我的常态。',
      links: ['boundary', 'nomad', 'pakistan'] },
    { id: 'hands', label: '指尖', type: 'associative', status: 'told',
      story: '在大公司里，我始终只是一台庞大机器上的一个零件。做贸易、在汽车公司管理项目的同时，一种遗憾也在累积——我从没有从头到尾用自己的双手做出过什么。会不会年纪越大越变得无力？于是我开始亲手动手制作——一个只靠脑子活着的人，开始以不同的方式信任器物，也信任这个世界。',
      links: ['bike', 'pm', 'tokyo'] },
    { id: 'survival', label: '生存', type: 'associative', status: 'seed',
      story: '我曾在没有基础设施、规则也截然不同的地方经营生意。生存从来不是按计划行事，而是计划崩溃之后依然能继续前行的能力。',
      links: ['png', 'nomad', 'trade'] },
    { id: 'bridge', label: '桥', type: 'associative', status: 'seed',
      story: '我一生都在两个世界之间架桥——语言与语言，文化与文化，买方与卖方。桥只有不完全属于任何一边，才能真正发挥作用。',
      links: ['interp', 'boundary', 'teaching'] },
    { id: 'drift', label: '漂流', type: 'associative', status: 'seed',
      story: '我从未走过一条直线。从物流到创业，从木材到自行车，轨迹总是弯曲的。看似漂流，回头看却是一张地图。',
      links: ['nomad', 'tokyo', 'drift'] },
    { id: 'adapt', label: '适应', type: 'associative', status: 'told',
      story: '即使面对足以撼动价值观的巨大变化，人终究会在其中适应。这是我十四岁在巴基斯坦学到的。适应不是屈服，而是旧世界崩塌之处、新想法萌芽生长的过程。',
      links: ['pakistan', 'boundary', 'survival'] },
    { id: 'commonsense', label: '常识', type: 'associative', status: 'told',
      story: '我曾称之为常识的东西，大多不过是我成长的那一个世界的规则。巴布亚新几内亚打破了那个边界之后，我变成了一个对任何事都不再理所当然的人。',
      links: ['png', 'stranger', 'survival'] },
    { id: 'islam', label: '伊斯兰', type: 'associative', status: 'told',
      story: '除了韩国和短暂游历过的几个欧洲国家，巴基斯坦是我所见过生活形态最为极端不同的地方。白天一到，人们便放下手中所有的事去祈祷。那是一种宗教先于一切的生活方式。十四岁的我在那面前百感交集——既陌生，又隐约意识到这个世界远比我所知道的更加广阔。',
      links: ['pakistan', 'stranger', 'adapt'] },
    { id: 'freedom', label: '自由', type: 'associative', status: 'told',
      story: '正如自行车之于我是自由的象征，我一直都被自由和挑战新事物所吸引。不被固定在一处，用自己的双手决定方向——这是驱动我一生的理想。',
      links: ['bike', 'nomad', 'drift', 'english'] },
    { id: 'nuance', label: '语感', type: 'associative', status: 'told', fresh: true,
      story: '说韩语时我最谨慎的原因之一是语感。只有懂韩语的人才听得出的微妙措辞，可能会伤到别人——这种担心一直跟着我。',
      links: ['multiling', 'boundary', 'teaching'] },
    { id: 'culture', label: '文化', type: 'associative', status: 'told', fresh: true,
      story: '我总对学生说——不要把语言当作机械翻译来学，要在文化环境和语境里去学。说外语时性格改变，也是发生在这个文化里面的事。',
      links: ['teaching', 'multiling', 'bridge', 'context'] },
    { id: 'trust', label: '信任', type: 'associative', status: 'seed',
      story: '和上百家物流伙伴合作让我明白：在物流里，信任本身就是基础设施。贸易也一样——越过边境搬运的，与其说是货物，不如说是信任。',
      links: ['logi', 'trade', 'sales', 'boundary'] },
    { id: 'shock', label: '冲击', type: 'associative', status: 'told', fresh: true,
      story: '冲击并不是在那一刻到来的。像战场上的士兵一样，当时什么都感觉不到。真正的冲击是很久以后，回到日常生活时才来——那时才醒悟，自己当时连悲伤都没有感到。',
      links: ['malaria', 'png', 'commonsense'] },
    { id: 'travel', label: '旅行', type: 'associative', status: 'told', fresh: true,
      story: '在维也纳时，周五下班就背起背包跳上巴士或火车。一觉醒来到了另一个国家——每次都觉得像奇迹。这是从韩国不可能拥有的自由。',
      links: ['vienna', 'prague', 'croatia', 'nomad', 'freedom'] },
    { id: 'context', label: '语境', type: 'associative', status: 'told', fresh: true,
      story: '教语言时我从语境讲起。不是把词抠出来翻译——而是连同它出自什么文化、什么处境一起展示。',
      links: ['teaching', 'culture', 'multiling', 'interp'] },
    { id: 'war', label: '战争', type: 'associative', status: 'told', fresh: true,
      story: '同样是战争的痕迹，在克罗地亚留下的是奇怪感，在柬埔寨留下的却是悲伤。已经重建的美丽，与仍未摆脱的贫穷——是这份差异分出了不同的感受。',
      links: ['croatia', 'cambodia', 'commonsense'] },

    { id: 'salt', label: '盐', type: 'wildcard', status: 'told', fresh: true,
      story: '我开始卖喜马拉雅岩盐，是因为和巴基斯坦的缘分——我隐约觉得，比起别人，我或许能更好地打入那个国家。那时正是我最热衷学习贸易的时期。每天寻找新品项，把成本、物流费、关税和增值税一一算清，与韩国售价比较，追逐利润率最高的商品。后来在日本的市场调查中，我发现一款用喜马拉雅粉盐做的泡脚产品——一算利润率将近千倍，是我算过的所有品项里最高的。但光有利润率并不能撑起一门生意。需求预测很生疏，而且那是我的第一次创业。那次失败教会我一件事：人们真正想要的价值，和我想展示的价值，是两回事。',
      links: ['trade', 'pakistan', 'sales'] },
    { id: 'timber', label: '木材', type: 'wildcard', status: 'seed',
      story: '我在巴布亚新几内亚的锯木厂经手木材——伐树、锯木、卖木材。处理直接来自自然的原材料，需要一种和城市生意完全不同的感觉。',
      links: ['png', 'sales', 'survival'] },
    { id: 'noni', label: '诺丽', type: 'wildcard', status: 'seed',
      story: '这是我在巴新四处寻找投资项目时清单上的一项。诺丽果、咖啡、乌木、废铁，甚至跆拳道。在一个什么都能成为生意的地方，我学会了嗅出可能性的气味。',
      links: ['png', 'coffee', 'trade'] },
    { id: 'coffee', label: '咖啡', type: 'wildcard', status: 'seed',
      story: '巴新的高地是世界级的咖啡产区。咖啡曾在我的投资调研清单上。最终没有做成，但那时练就的市场眼光留了下来。',
      links: ['noni', 'png'] },
    { id: 'ebony', label: '乌木', type: 'wildcard', status: 'seed',
      story: '乌木，一种乌黑坚硬的木材。我曾在巴新把它当作投资项目考察过。稀有的东西，总是同时附带着故事和风险。',
      links: ['noni', 'timber', 'png'] },
    { id: 'taekwondo', label: '跆拳道', type: 'wildcard', status: 'seed',
      story: '说出来可能难以置信，跆拳道曾在我的巴新投资调查清单上——想象着把韩国的东西种进南太平洋。最终，它以另一种形式实现了——教语言和文化。',
      links: ['png', 'teaching', 'bridge'] },
    { id: 'scrap', label: '废铁', type: 'wildcard', status: 'seed',
      story: '废铁也曾是生意项目之一——在别人眼中的垃圾里看到价值。在废弃之物中重新发现用处的眼光，用在人身上，同样适用。',
      links: ['png', 'survival', 'trade'] },
    { id: 'subline', label: '限制', type: 'wildcard', status: 'seed',
      story: '一行字幕能容纳的字数是固定的。在这个限制之内，既要保留原文的意思，也要保留情感。限制不是创意的反面，而是创意的条件。',
      links: ['subtitle', 'interp'] },
    { id: 'chain', label: '链条', type: 'wildcard', status: 'seed',
      story: '自行车链条是个沾满油污和灰尘的部件，但没有它，哪里都去不了。那些不起眼却让一切运转起来的东西——我一直被这样的东西吸引。',
      links: ['bike', 'hands'] },
    { id: 'trade', label: '贸易', type: 'wildcard', status: 'seed',
      story: '我一生都在把东西运过边境——盐、果汁原液、木材、店铺装置。贸易运送的从来不是货物，而是跨越边境的信任。',
      links: ['salt', 'sales', 'logi', 'boundary'] },
    { id: 'guesthouse', label: '民宿', type: 'wildcard', status: 'seed',
      story: '我在杭州开了一家民宿。活动策划、营销、修自行车，全都一个人包办。看起来像是多线作战，实际上是一种把整个生意当作一个整体来理解的训练。',
      links: ['hangzhou', 'hands', 'survival'] },
    { id: 'bikery', label: 'Bikery', type: 'wildcard', status: 'seed',
      story: '我在杭州开了 Bikery Guest House。名字就说明了一切——自行车和民宿在同一屋檐下。活动策划、营销、维修，都是我一个人扛。对一个漂泊很久的人来说，这是第一次给真正属于自己的空间起名字。',
      links: ['hangzhou', 'guesthouse', 'bike', 'hands'] },
    { id: 'startup', label: '创业', type: 'wildcard', status: 'told', fresh: true,
      story: '第一次创业是卖喜马拉雅岩盐。利润率将近千倍，但生意还是做不成。那次失败教会我：人们想要的价值，和我想展示的价值，是两回事。',
      links: ['salt', 'trade', 'sales', 'pakistan'] },
    { id: 'navy', label: '海军', type: 'wildcard', status: 'told',
      story: '父亲是海军军官。我们家住在镇海，后来我也在那里服过兵役。生命开始的地方和服役的地方重叠在一起。',
      links: ['jinhae', 'masan', 'pakistan', 'boundary'] },
    { id: 'dog', label: '狗', type: 'wildcard', status: 'told', fresh: true,
      story: '都柏林那栋两层小楼里养着两只大狗。在沙发上坐着，它们随时会跑过来玩；散步时间一到又跟着出门。第一次出国的记忆是两只狗，不是某个人——这也不坏。',
      links: ['ireland', 'nomad'] },
    { id: 'winter', label: '冬天', type: 'wildcard', status: 'told', fresh: true,
      story: '在布拉格行李被偷之后，欧洲的冬天格外凛冽。一天往往以最便宜的餐酒和烤肉卷、裹在被子里吃完收场。在韩国会觉得奢侈的东西，在寒冷里成了小小的幸福。',
      links: ['prague', 'vienna', 'survival'] },
    { id: 'star', label: '星', type: 'wildcard', status: 'told', fresh: true,
      story: '在莫尔兹比港，入夜后断电，工厂的灯也灭了。捡木屑生火，抬头看格外明亮的星星——那就是那里一天的结束。',
      links: ['png', 'survival', 'beer'] },
    { id: 'beer', label: '啤酒', type: 'wildcard', status: 'told', fresh: true,
      story: '布拉格车站旁公园里的一罐原装百威，在行李被偷的那晚好得不可思议。在巴新，一两瓶啤酒伴着漆黑的天空，就是一天的尾声。',
      links: ['prague', 'png', 'winter', 'star'] },
    { id: 'malaria', label: '疟疾', type: 'wildcard', status: 'told', fresh: true,
      story: '一起工作的同事曾来找我，想借钱给孩子买疟疾药。我没有借，不久后那个孩子去世了。奇怪的不是那一刻本身。就像战场上的士兵当时感觉不到死亡，我当时也什么都感觉不到。真正的冲击是很久以后，结束了那里的生活回到韩国的日常时才到来——在一个孩子的死亡面前，我当时既没有悲伤也没有痛苦，这个迟来的醒悟。这件事比死亡本身更久地跟着我。',
      links: ['png', 'commonsense', 'survival'] },
    { id: 'ecoventure', label: '生态', type: 'wildcard', status: 'seed', fresh: true,
      story: '和垃圾一起走的冒险。不只是徒步——边走边捡起被丢下的东西，那就是生态冒险。',
      links: ['trash', 'plogging', 'hangzhou', 'survival'] },
    { id: 'trash', label: '垃圾', type: 'wildcard', status: 'seed', fresh: true,
      story: '在别人叫作垃圾的东西里看见价值。路上被丢下的、被弃的物件、被弃的瞬间——再把它们捡回手里，就是捡跑，也是生态冒险。',
      links: ['ecoventure', 'plogging', 'scrap'] },
    { id: 'plogging', label: '捡跑', type: 'wildcard', status: 'seed', fresh: true,
      story: '边跑边走边捡垃圾。身体和路一起变干净的感觉。可以一个人做，也可以把人聚起来一起做。',
      links: ['ecoventure', 'trash', 'hangzhou'] },
  ],

  thoughts: [
    { id: 'th1', text: '在5大洲工作15年学到的：语言和文化和技术规格同样重要。一份合同有一半，来自信任和理解。',
      tags: ['multiling', 'boundary', 'bridge'], daysAgo: 0 },
    { id: 'th2', text: '摆弄自行车时的感受——懂得用双手修理东西的人，信任世界的方式不同。对实物的理解，构成了思考的根基。',
      tags: ['bike', 'hands'], daysAgo: 1 },
    { id: 'th3', text: '同时卖盐和果汁原液的那段时间：哪怕是很小的生意，只要理解了它的整个周期，就能重新读懂任何一个行业。',
      tags: ['salt', 'trade', 'sales'], daysAgo: 2 },
    { id: 'th4', text: '一旦习惯了以异乡人的身份生活，就没什么是理所当然的，于是看到的更多。不适感，很久以前就成了默认状态。',
      tags: ['stranger', 'boundary', 'nomad'], daysAgo: 3 },
    { id: 'th5', text: '看似漂流的轨迹，回头看却是一张地图。不是直线，也自有方向。',
      tags: ['drift', 'nomad'], daysAgo: 4 },
    { id: 'th6', text: '在最陌生的地方，想法改变得最大。巴基斯坦和巴布亚新几内亚——那些从未让我感到舒适的地方，塑造了我。',
      tags: ['pakistan', 'png', 'stranger'], daysAgo: 5 },
    { id: 'th7', text: '在巴基斯坦我明白了，即使身处巨变之中人也会适应；在巴布亚新几内亚我明白了，我的"常识"不过是多么狭小的一个世界的规则。陌生，始终是我的老师。',
      tags: ['adapt', 'commonsense', 'pakistan', 'png'], daysAgo: 0 },
    { id: 'th8', text: '在庞大组织中做的越是一颗螺丝钉，就越想亲手从头到尾做出点什么。我通过亲自设计自行车车架解了这个渴——自由，说到底就是用自己的双手决定方向。',
      tags: ['pm', 'bike', 'hands', 'freedom'], daysAgo: 0 },
    { id: 'th9', text: '在出生的城市，我一天也没住过，此后一生都在迁徙。没有故乡不是一种缺失，而是一个不属于任何地方、因而能看见所有地方的位置。',
      tags: ['boundary', 'masan', 'nomad'], daysAgo: 0 },
    { id: 'th10', text: '冲击并非在那一刻到来。像战场上的士兵一样，我在当下什么都没感觉到。真正的冲击，是很久之后回到日常生活，意识到自己当时连悲伤都没有感受到的时候，才降临的。',
      tags: ['malaria', 'png', 'commonsense'], daysAgo: 0 },
    { id: 'th11', text: '第一次出国的经历留下的不是某个人，而是两只狗。重要的记忆，总是坐在你意想不到的地方。',
      tags: ['ireland', 'nomad'], daysAgo: 0 },
    { id: 'th12', text: '行李被偷、求助无门的那个布拉格夜晚，在公园里喝的一罐百威，味道出奇地好。即使在最艰难的时刻，身体也总能从微小的事物中找到慰藉。',
      tags: ['prague', 'stranger', 'survival'], daysAgo: 0 },
    { id: 'th13', text: '找到一款利润率千倍的产品，并不等于生意能成。第一次创业失败教会我的：人们想要的价值，和我想展示的价值，是两回事。',
      tags: ['salt', 'trade'], daysAgo: 0 },
    { id: 'th14', text: '丢东西后那个拮据的冬天，裹着被子吃最便宜的酒和烤肉卷。在韩国会是种奢侈的东西，在欧洲的寒冷里却成了一点微小的幸福。',
      tags: ['prague', 'vienna'], daysAgo: 0 },
    { id: 'th15', text: '同样是战争的痕迹，在克罗地亚留下的是奇怪感，在柬埔寨留下的却是悲伤。已经重建的美丽，与仍未摆脱的贫穷——是这份差异分出了不同的感受。',
      tags: ['croatia', 'cambodia'], daysAgo: 0 },
    { id: 'th16', text: '口译最难的，是用我自己的嘴说出别人的想法和话语。哪怕是我不认同的话，一旦用我的声音说出来，就感觉像是我说的。正是那份不适，成了我想用外语说出自己的话的动力。',
      tags: ['interp', 'multiling'], daysAgo: 0 },
    { id: 'th17', text: '说英语时出现的是最自然的我，说日语时是过分小心的我，说中文时是过分大胆的我。韩语虽是我教的语言，却是我说起来最谨慎的——有些伤害，只在语感相通的人之间才会发生。',
      tags: ['multiling', 'boundary', 'teaching'], daysAgo: 0 },
    { id: 'th18', text: '每个人说外语时性格都会变，只是程度不同。所以我对学生说——语言不是靠机械翻译学会的，而是通过它的文化环境和语境学会的。',
      tags: ['teaching', 'multiling'], daysAgo: 0 },
  ],

  openQuestions: [
    { node: 'interp', q: '在那些不得不翻译自己并不认同的话的时刻里，有没有一个印象最深的具体场景？' },
    { node: 'multiling', q: '说中文时那个过分大胆的你，有没有惹出过什么故事？' },
    { node: 'ireland', q: '初中时的第一次出国旅行——途经英国、法国、香港最终落脚都柏林——那趟旅行是怎么计划的？' },
    { node: 'trade', q: '在学习贸易的那段时间里，除了盐，你还追逐过哪些意想不到的品项？' },
    { node: 'chain', q: '修自行车的时候，有没有哪个瞬间让你特别自豪？' },
    { node: 'subline', q: '做字幕的时候，有没有哪句话是最难翻译的？' },
    { node: 'cambodia', q: '能不能多讲讲在柬埔寨看到的那些古迹，还有你是怎么碰上那两个美国游客的？' },
    { node: 'croatia', q: '除了克罗地亚，那段时期还有没有其他让你印象深刻的东欧国家？' },
  ],

  combos: [
    { ids: ['pm', 'hands', 'bike'], title: '从零件，到制造者',
      story: '作为庞大汽车项目中的一个零件工作着，我怀揣着一种遗憾——从没有从头到尾用自己的双手做出过什么。三十岁那年，我辞去稳定的项目经理职位，去东京亲手设计自行车车架，那是我对这份遗憾的回答。当我开始用指尖去理解这个世界，我终于从一颗零件，变成了一个制造者。',
      weights: { pm: 0.8, hands: 1.15, bike: 1.35 } },
    { ids: ['pakistan', 'islam', 'adapt'], title: '价值观动摇的十四岁',
      story: '十四岁那年跟随父亲抵达伊斯兰堡，我第一次看到宗教如何彻底塑造一个社会的生活方式。白天一到，所有人都放下工作去祈祷——面对这一幕，我的价值观被彻底动摇。但即使在这动摇之中，人终究会适应下来——而我在那个年纪，用身体明白了：适应过程中萌生的无数想法，会改变一个人生活的方式本身。',
      weights: { pakistan: 1.35, islam: 1.05, adapt: 1.15 } },
    { ids: ['png', 'malaria', 'commonsense'], title: '黑暗与星空下崩塌的常识',
      story: '在莫尔兹比港的工厂旁边，生与死靠得很近。一位同事让我借钱给孩子买疟疾的药，我没有借，那孩子后来去世了。那一刻我什么都没感觉到——像战场上的士兵一样。真正的冲击是回到韩国之后才到来的：一个迟来的领悟，那时的我竟连悲伤都没有感受到。这份自觉，重新划定了我所深信的"常识"的边界。',
      weights: { png: 1.15, malaria: 1.35, commonsense: 1.05 } },
    { ids: ['boundary', 'masan', 'nomad'], title: '没有故乡的人',
      story: '我出生在马山，却一天也没在那里生活过——只是因为镇海没有妇产科医院。从那时起，我就是一个不完全属于任何地方的人。此后一生都在跨越国境。没有故乡不是一种缺失，而是一个无论在哪里都可以既是里面也是外面的位置——边界人，最能描述我的那个词。',
      weights: { boundary: 1.4, masan: 1.0, nomad: 0.9 } },
    { ids: ['salt', 'pakistan', 'trade'], title: '利润率千倍的失败',
      story: '若不是和巴基斯坦的缘分，我根本不会想到去卖喜马拉雅岩盐——我隐约觉得，比起别人，我或许能更好地打入那个国家。那正是我最热衷学习贸易的时期。我在日本市场调查中发现的一款喜马拉雅粉盐泡脚产品，利润率将近千倍。但光有利润率并不能撑起一门生意——这是我从第一次创业的失败中学到的。',
      weights: { salt: 1.35, pakistan: 0.9, trade: 1.05 } },
    { ids: ['prague', 'stranger', 'survival'], title: '被偷的行李，和一罐啤酒',
      story: '行李箱在布拉格中央车站被偷时，挤满人的车站里没有一个人帮我。那是我第一次明白求助无门的滋味——异乡人的生活就是这样。拖着剩下的沉重行李，一屁股坐在公园长椅上喝的那罐百威，在那艰难的一刻竟出奇地好喝。生存，就是计划崩溃之后依然继续前行，偶尔，也从微小的事物中找到慰藉。',
      weights: { prague: 1.3, stranger: 0.95, survival: 1.05 } },
    { ids: ['ireland', 'pakistan', 'nomad'], title: '两只狗与动摇的价值观，我最初的两个国家',
      story: '初中二年级第一次出国，在都柏林住了一个月。仅仅一两年之后，我又跟随父亲住在伊斯兰堡。都柏林两只狗自由奔跑的平静山坡，和伊斯兰堡价值观被动摇的陌生午后——这两者并列，成了我最初的海外经历。从那时起，我不再是一个留在一处的人，而是一个不断迁移的人。',
      weights: { ireland: 1.0, pakistan: 1.25, nomad: 1.1 } },
    { ids: ['interp', 'multiling', 'freedom'], title: '从别人的话，到我自己的话',
      story: '口译是用我自己的嘴说出别人想法的工作。哪怕是我不认同的话，一旦用我的声音说出来，就感觉像是我说的——既没有失去自己，也没能完全抽离，我站在两者之间的某个地方。正是那份不适成了动力：想用我自己的声音，用外语，说出我自己的话。最自然的我出现在英语里，这并非偶然——那是我最年少时学的语言，象征着自由。语言对我来说，从一开始就是一个关于自由的问题。',
      weights: { interp: 1.25, multiling: 1.05, freedom: 0.9 } },
    { ids: ['teaching', 'multiling', 'bridge'], title: '站在桥上，教人如何架桥',
      story: '韩语、英语、中文、日语——这四种语言几乎像四种不同的人格。如今在杭州师范大学教韩语，并不只是传授语法，而是在语言与语言、文化与文化之间架桥。一个一生都生活在这座桥上的人，如今正教着别人如何架起自己的桥。',
      weights: { teaching: 1.2, multiling: 1.0, bridge: 1.15 } },
  ],
};

if (typeof window !== 'undefined') window.DATA_ZH = DATA_ZH;
