/* English translation of data.js — same ids/structure/links, translated label/story/text/title only. */

const DATA_EN = {
  profile: {
    name: 'Paul Bhang',
    hangul: 'Bhang Sanghoon',
    tagline: '15 years · 5 continents · 4 languages',
    places: 'HANGZHOU · SEOUL',
    hero1: 'Choose a word,',
    hero2: 'and you\'ll see me.',
    heroSub: 'The words drifting through my head. <b>Choose, and connect.</b>',
    faces: 'LINGUIST · TRADER · MAKER · EDUCATOR · STORYTELLER · EXPLORER',
    email: 'bikeryhz@hotmail.com',
    location: 'Hangzhou, China · Incheon, Korea',
    contentAsOf: '2026.07.17',
  },

  nodes: [
    { id: 'interp', label: 'Interpretation & Translation', type: 'core', status: 'seed',
      story: "For a long time, I stood between languages — Korean and English, sometimes Chinese. At the negotiation table I learned that interpreting isn't about moving words across; it's about making two people trust each other.",
      links: ['multiling', 'bridge', 'vienna', 'shanghai'] },
    { id: 'multiling', label: 'Multilingual', type: 'core', status: 'seed',
      story: "Korean is my mother tongue, English is a language that's become second nature, and Chinese and Japanese are ones I picked up along the way. The four languages feel almost like four different personalities. Switch the language, and the grain of my thinking shifts too.",
      links: ['interp', 'teaching', 'boundary'] },
    { id: 'sales', label: 'B2B Sales', type: 'core', status: 'seed',
      story: "I've sold everything from salt to timber, retail fixtures, and auto parts. The product kept changing, but the core of it never did — figuring out what the other side actually wants.",
      links: ['salt', 'timber', 'shanghai', 'trade'] },
    { id: 'pm', label: 'Project Management', type: 'core', status: 'told',
      story: "Managing the Beijing Hyundai project, I realized that half of what looked like technical problems were actually cultural ones. It's the person who can mediate who keeps a project alive. But working as one part of a massive organization, a quiet regret grew alongside it — I had never made anything from start to finish with my own hands.",
      links: ['shanghai', 'interp', 'hands', 'boundary'] },
    { id: 'subtitle', label: 'Video Subtitling', type: 'core', status: 'seed',
      story: "For six years I made subtitles between Korean and English. Translation turned out to be less about language and more about timing, rhythm, and the implication that never fits on screen. A single line holds far less than you'd think.",
      links: ['subline', 'interp', 'hangzhou'] },
    { id: 'bike', label: 'Bicycles', type: 'core', status: 'told',
      story: "At thirty-two I enrolled in a bicycle-building school in Tokyo. I designed a frame myself and built it exactly as I'd imagined. A bicycle was, to me, a symbol of freedom — going anywhere, taking on something new. It was the object that matched my ideals most closely. While others were climbing the career ladder, I was assembling wheels — making, for the first time, something entirely my own.",
      links: ['tokyo', 'hands', 'freedom', 'chain'] },
    { id: 'logi', label: 'Logistics', type: 'core', status: 'seed',
      story: "Handling air and sea freight, I worked with over a hundred partner companies. Logistics is a world where trust itself is the infrastructure. One mistake can stop someone on the other side of the planet in their tracks.",
      links: ['vienna', 'trade', 'survival'] },
    { id: 'teaching', label: 'Language Education', type: 'core', status: 'seed',
      story: "These days I teach Korean at Hangzhou Normal University. Teaching a language isn't really about grammar — it's opening a door into a culture. Soft power starts in the classroom.",
      links: ['multiling', 'hangzhou', 'bridge'] },

    { id: 'pakistan', label: 'Pakistan', type: 'place', era: '1997–1998', status: 'told',
      story: "When my father, a navy officer, was posted to Pakistan, fourteen-year-old me ended up living in Islamabad. The first shock was seeing how completely Islam shaped every part of people's lives. In the face of change so vast it shook my values to the core, I learned — for the first time, in my own body, at that age — that people adapt anyway, and that the countless thoughts blooming out of that adaptation end up reshaping the whole way you live.",
      links: ['stranger', 'boundary', 'adapt', 'islam'] },
    { id: 'png', label: 'Papua New Guinea', type: 'place', era: '2009–2010', status: 'told', fresh: true,
      story: "Life in Port Moresby was even more extreme than Pakistan. I lived inside the timber mill compound, in a house converted from a trade container that had shipped machinery over from Korea. At night the power would cut and the mill lights would go dark, and a very long, pitch-black night would follow. A typical day there meant gathering wood scraps for a fire, drinking a bottle or two of beer that was surprisingly expensive at the time, and looking up at stars that were unusually bright. Death wasn't far from where we worked, and malaria was far too common. Under that darkness and those stars, I realized that everything I'd believed was 'common sense' had only ever been the rules of the one world I happened to grow up in.",
      links: ['timber', 'survival', 'stranger', 'commonsense'] },
    { id: 'vienna', label: 'Vienna', type: 'place', era: '2005–2007', status: 'told', fresh: true,
      story: "In my mid-twenties I set up an airport branch office in Vienna, alone. Building a company from scratch in an unfamiliar city. In the heart of Europe, I was a stranger — and that turned out to be a weapon. On weekends I'd shoulder a single backpack and jump on a bus or train the moment I clocked out on Friday. Crossing a border overland was something you simply couldn't do from Korea, so waking up in a different country each time felt like a small marvel, every single time. That's how I drifted through corner after corner of Eastern Europe — until my bag was stolen in Prague.",
      links: ['logi', 'stranger', 'boundary', 'prague', 'croatia'] },
    { id: 'prague', label: 'Prague', type: 'place', era: '2005–2007', status: 'told', fresh: true,
      story: "It happened at Prague's main train station, Czech Republic, on my way to Vienna. I was on the phone to Korea when a man beside me kept nudging me, trying to sell some kind of digital camera. We couldn't understand each other, so I waved him off. After a few rounds of that, by the time I finished the call, one of my suitcases was gone — a gang had taken it. The station was packed with people, but no one helped, and I ran around in circles without finding it. I went to the police, but there was no CCTV back then. That was the first time I understood the feeling of being unable to get help from anyone. I dragged my remaining heavy luggage to a park beside the station, sat down, and cracked open an original Budweiser bought at a nearby store — back then something you could only get in Czechia and Slovakia. In that hard moment, it tasted strangely good. My money and my Eurail pass had been in that bag. From then on I had to spend as little as possible. I crashed for a while at a friend's place while he was away doing his military service — European winter was brutal and the heating barely worked. Most days that winter ended the same way: the cheapest table wine and a kebab, eaten in bed wrapped in a blanket. Before the theft I'd been leaving for a different country every single weekend — the gap between that freedom and this threadbare winter was stark. And yet that wine and that kebab were a luxury I couldn't have justified back home in Korea. It was a stretch of time where poverty and a kind of foreign abundance sat side by side.",
      links: ['vienna', 'stranger', 'survival'] },
    { id: 'croatia', label: 'Croatia', type: 'place', era: '2005–2007', status: 'told', fresh: true,
      story: "Of all the countries I passed through on weekend trips from Vienna, this is the one that's stayed sharpest. It was before that famous Korean travel show had filmed there, so hardly anyone I knew had heard of it. I rode a boat along the coast, got off, and wandered a small harbor town — white laundry strung on lines between houses, a cat lounging by a boat-repair yard, and bullet holes still marking the outer walls of the houses. I vaguely knew there'd been a war, but I hadn't expected to see its scars still sitting there. What struck me wasn't sadness — just how strange it was, those bright faces beside those marks. The country had already been rebuilt, beautifully.",
      links: ['vienna', 'nomad', 'stranger'] },
    { id: 'cambodia', label: 'Cambodia', type: 'place', era: 'around 2013', status: 'told', fresh: true,
      story: "Before I moved back to Korea after finishing up in Shanghai, I traveled through Cambodia. A country whose glorious past history had become its only remaining source of income; I kept passing people on the street with physical disabilities. At one of the temple sites, I overheard two American tourists talking — mocking, sarcastic jokes. They probably assumed the Cambodians around them couldn't understand English. Or maybe they understood and just didn't care. I'm not talking about Americans in general — but a country's image ends up shaped, in large part, by the handful of people you happen to run into. The same kind of 'scar of war' that had felt merely strange in Croatia landed here as sadness.",
      links: ['boundary', 'stranger', 'commonsense'] },
    { id: 'tokyo', label: 'Tokyo', type: 'place', era: '2014–2016', status: 'told', fresh: true,
      story: "Deciding to go to Tokyo wasn't one dramatic moment. My job as a project manager at the car company was actually a good one — decent pay, good treatment. But life gradually grew dull. Days without any felt passion kept piling up. When I turned thirty, I kept thinking that if I didn't make one big change now, it would be too late. So I folded up that stability and went back to being a student, in Tokyo.",
      links: ['bike', 'hands', 'pm', 'drift'] },
    { id: 'shanghai', label: 'Shanghai', type: 'place', era: '2010–2013', status: 'seed',
      story: "After exporting retail fixtures to Europe, I became a program manager at an automotive safety-parts company. Interpreter between Korean and Chinese business cultures — that was my real title.",
      links: ['sales', 'pm', 'interp'] },
    { id: 'hangzhou', label: 'Hangzhou', era: '2017–present', type: 'place', status: 'seed',
      story: "I opened a guesthouse, made subtitles, and now I teach at a university. The city where someone who wandered for so long first put down roots. A chapter still being written.",
      links: ['teaching', 'subtitle', 'guesthouse'] },
    { id: 'ireland', label: 'Ireland', type: 'place', era: 'around 1996', status: 'told', fresh: true,
      story: "In my second year of middle school, I left the country for the first time. Passing briefly through England, France, and Hong Kong, I arrived in Dublin and lived there for a month. Even though it was the capital, there was a hillside walking path right behind the house, and that two-story home had two large dogs. Sitting on the couch, they'd wander over to play whenever they felt like it, then tag along at walk time — that image is still the sharpest memory I have. That my first overseas experience is remembered through two dogs rather than any person isn't a bad thing at all.",
      links: ['pakistan', 'nomad', 'stranger'] },
    { id: 'jinhae', label: 'Jinhae', type: 'place', era: '1983 · 2003–2005', status: 'told',
      story: "The place where my life began, and the place I later returned to for military service in the navy. My father was a naval officer, so our family lived in Jinhae. But I wasn't actually born there — Jinhae had no maternity hospital back then, so my mother crossed over to Masan to have me. From the very start, I was someone who never fully belonged to any single place.",
      links: ['boundary', 'masan', 'stranger'] },
    { id: 'masan', label: 'Masan', type: 'place', era: '1983', status: 'told',
      story: "My hometown, on paper. But I've never lived there for a single day. It's simply the place my mother crossed over to briefly, to give birth to me, because Jinhae had no maternity hospital. The place I was born and the place I would live were mismatched from the very start — maybe that was the first metaphor of my life.",
      links: ['jinhae', 'boundary', 'nomad'] },

    { id: 'nomad', label: 'Nomad', type: 'associative', status: 'seed',
      story: "I've never stayed long in one city — Seoul, Vienna, Port Moresby, Shanghai, Tokyo, Hangzhou. The wandering was never escape; it was collecting. Each move, I picked up a different way of living.",
      links: ['drift', 'stranger', 'survival'] },
    { id: 'boundary', label: 'Border-Dweller', type: 'associative', status: 'told',
      story: "When someone asks where I'm from, I usually say I don't have a hometown. I've never lived in Masan, where I was born, and I've spent my whole life since moving between countries. Never fully inside anywhere, never fully outside either — Korean, yet teaching in China; a salesman, yet also a mechanic. There are things only someone standing on the boundary can see. If I had to pick one word that describes me best, this is probably it.",
      links: ['stranger', 'bridge', 'nomad', 'masan'] },
    { id: 'stranger', label: 'The Outsider', type: 'associative', status: 'seed',
      story: "I'm used to living as a stranger. An outsider takes nothing for granted, and so sees more. Discomfort became my default setting a long time ago.",
      links: ['boundary', 'nomad', 'pakistan'] },
    { id: 'hands', label: 'With My Own Hands', type: 'associative', status: 'told',
      story: "At big companies, I was always one part of a massive machine. Even while trading goods and managing projects at an auto company, a regret kept building — that I'd never made anything from start to finish with my own hands. I worried I might grow helpless with age. So I started making things with my own hands — and someone who'd lived only in his head began to trust objects, and the world, differently.",
      links: ['bike', 'pm', 'tokyo'] },
    { id: 'survival', label: 'Survival', type: 'associative', status: 'seed',
      story: "I've run businesses in places with no infrastructure, where the rules were different. Surviving was never about things going to plan — it was the ability to keep moving after the plan had already fallen apart.",
      links: ['png', 'nomad', 'trade'] },
    { id: 'bridge', label: 'Bridge', type: 'associative', status: 'seed',
      story: "My whole life has been building bridges between two worlds — language and language, culture and culture, the buyer's side and the seller's. A bridge only does its job if it doesn't fully belong to either side.",
      links: ['interp', 'boundary', 'teaching'] },
    { id: 'drift', label: 'Drift', type: 'associative', status: 'seed',
      story: "I've never lived in a straight line. From logistics to founding a company, from timber to bicycles — the path always curved. It looked like drifting, but looking back, it was a map all along.",
      links: ['nomad', 'tokyo', 'drift'] },
    { id: 'adapt', label: 'Adaptation', type: 'associative', status: 'told',
      story: "Even in the face of change vast enough to shake your values, people adapt within it. That's what I learned at fourteen, in Pakistan. Adaptation isn't surrender — it's the process by which new thoughts bloom from the ground where an old world has collapsed.",
      links: ['pakistan', 'boundary', 'survival'] },
    { id: 'commonsense', label: 'Common Sense', type: 'associative', status: 'told',
      story: "What I used to call common sense was mostly just the rules of the one world I grew up in. After Papua New Guinea broke down that boundary, I became someone who takes nothing for granted.",
      links: ['png', 'stranger', 'survival'] },
    { id: 'islam', label: 'Islam', type: 'associative', status: 'told',
      story: "Aside from Korea and a few European countries I briefly traveled through, Pakistan was the most extremely different form of life I'd seen. When day came, people stopped whatever they were doing to pray. A way of life where religion comes before everything else. Fourteen-year-old me felt a tangle of emotions in front of that — unfamiliarity, alongside a hazy realization that the world was far bigger than what I'd known.",
      links: ['pakistan', 'stranger', 'adapt'] },
    { id: 'freedom', label: 'Freedom', type: 'associative', status: 'told',
      story: "Just as a bicycle was a symbol of freedom to me, I've always been drawn to freedom and the challenge of the new. Not being tied to one place; setting my own direction with my own hands. That's been the ideal that's driven me my whole life.",
      links: ['bike', 'nomad', 'drift'] },

    { id: 'salt', label: 'Salt', type: 'wildcard', status: 'told', fresh: true,
      story: "I started selling Himalayan rock salt because of my connection to Pakistan — I had a hunch I could approach that country a bit better than others could. That was when I was learning trade most passionately. Every day I hunted for new items, calculating cost, shipping, tariffs, and VAT one by one, comparing against Korean retail prices, chasing whatever product had the highest margin. Then, in a market survey in Japan, I found a foot-soak product made from Himalayan pink salt — the margin worked out to nearly a thousandfold, the best of anything I'd calculated up to that point. But margin alone didn't make a business. My demand forecasting was clumsy, and it was my first venture. From that failure I learned one thing: the value people actually want and the value I want to show them are two different things.",
      links: ['trade', 'pakistan', 'sales'] },
    { id: 'timber', label: 'Timber', type: 'wildcard', status: 'seed',
      story: "I handled timber at a sawmill in Papua New Guinea — felling trees, cutting them, selling them. Working with raw material straight from nature demanded an entirely different sense than city business.",
      links: ['png', 'sales', 'survival'] },
    { id: 'noni', label: 'Noni', type: 'wildcard', status: 'seed',
      story: "One of the items on the list while I scoured PNG for something to invest in. Noni, coffee, ebony, scrap metal, even taekwondo. In a place where anything could become a business, I learned to sniff out possibility.",
      links: ['png', 'coffee', 'trade'] },
    { id: 'coffee', label: 'Coffee', type: 'wildcard', status: 'seed',
      story: "The highlands of PNG are a world-class coffee-growing region. Coffee was on my investment survey list. I never ended up going through with it, but the eye for reading a market that I developed then stayed with me.",
      links: ['noni', 'png'] },
    { id: 'ebony', label: 'Ebony', type: 'wildcard', status: 'seed',
      story: "Ebony — black, dense wood. I looked into it as an investment item in PNG. Anything rare always came bundled with both a story and a risk.",
      links: ['noni', 'timber', 'png'] },
    { id: 'taekwondo', label: 'Taekwondo', type: 'wildcard', status: 'seed',
      story: "Hard to believe, but taekwondo was on my PNG investment survey list — imagining planting something Korean in the South Pacific. In the end, it came true in a different form: teaching language and culture.",
      links: ['png', 'teaching', 'bridge'] },
    { id: 'scrap', label: 'Scrap Metal', type: 'wildcard', status: 'seed',
      story: "Scrap metal was a business item too — seeing value in what others call trash. The eye that finds new use in what's been discarded works the same way on people.",
      links: ['png', 'survival', 'trade'] },
    { id: 'subline', label: 'One Line of Subtitle', type: 'wildcard', status: 'seed',
      story: "There's a fixed limit to how many characters one line of subtitle can hold. Within that constraint, I had to preserve both the meaning and the feeling of the original. Constraint isn't the opposite of creativity — it's the condition for it.",
      links: ['subtitle', 'interp'] },
    { id: 'chain', label: 'Chain', type: 'wildcard', status: 'seed',
      story: "A bicycle chain is a part that gets dirty with oil and dust, but without it you go nowhere. Things that are unnoticed yet keep everything moving — I've always been drawn to those.",
      links: ['bike', 'hands'] },
    { id: 'trade', label: 'Trade', type: 'wildcard', status: 'seed',
      story: "My whole life I've been moving things across borders — salt, juice concentrate, timber, retail fixtures. Trade was never about moving goods; it was about moving trust across a border.",
      links: ['salt', 'sales', 'logi', 'boundary'] },
    { id: 'guesthouse', label: 'Guesthouse', type: 'wildcard', status: 'seed',
      story: "I opened a guesthouse in Hangzhou. I did everything myself — events, marketing, even bike repair. It looked like multitasking, but it was really training in understanding an entire business as one body.",
      links: ['hangzhou', 'hands', 'survival'] },
    { id: 'malaria', label: 'Malaria', type: 'wildcard', status: 'told', fresh: true,
      story: "A coworker once came to me asking to borrow money for his child's malaria medicine. I didn't lend it, and not long after, the child passed away. What was strange wasn't that moment itself. Just as a soldier on a battlefield doesn't register death in the moment, I too felt nothing at the time. The real shock came much later, after I'd finished that life there and returned to ordinary days in Korea — the belated realization that, in front of a child's death, I had felt neither grief nor pain back then. That fact followed me longer than the death itself did.",
      links: ['png', 'commonsense', 'survival'] },
  ],

  thoughts: [
    { id: 'th1', text: "What 15 years working across 5 continents taught me: language and culture matter as much as technical specs. Half of any contract comes from trust and understanding.",
      tags: ['multiling', 'boundary', 'bridge'], daysAgo: 0 },
    { id: 'th2', text: "What I felt working on bicycles — someone who can fix things with their hands trusts the world differently. Physical understanding lays the floor for thinking itself.",
      tags: ['bike', 'hands'], daysAgo: 1 },
    { id: 'th3', text: "Back when I sold salt and juice concentrate at the same time: once you understand the full cycle of even a small business, you can re-read any industry.",
      tags: ['salt', 'trade', 'sales'], daysAgo: 2 },
    { id: 'th4', text: "Once you get used to living as an outsider, nothing is taken for granted, so you see more. Discomfort became my default a long time ago.",
      tags: ['stranger', 'boundary', 'nomad'], daysAgo: 3 },
    { id: 'th5', text: "The path that looked like drifting turned out, in hindsight, to be a map. It didn't need to be a straight line to have a direction.",
      tags: ['drift', 'nomad'], daysAgo: 4 },
    { id: 'th6', text: "My thinking changed the most in the places that felt most unfamiliar. Pakistan and Papua New Guinea — places I was never comfortable in — are what made me.",
      tags: ['pakistan', 'png', 'stranger'], daysAgo: 5 },
    { id: 'th7', text: "In Pakistan I learned that people adapt even amid enormous change; in Papua New Guinea I learned how narrow a world my 'common sense' had actually been the rules of. Unfamiliarity has always been my teacher.",
      tags: ['adapt', 'commonsense', 'pakistan', 'png'], daysAgo: 0 },
    { id: 'th8', text: "The more I worked as one part of a massive organization, the more I wanted to make something from start to finish with my own hands. I quenched that thirst by designing a bicycle frame myself — freedom, in the end, meant setting my own direction with my own hands.",
      tags: ['pm', 'bike', 'hands', 'freedom'], daysAgo: 0 },
    { id: 'th9', text: "I never lived a single day in the city I was born in, and I've spent my whole life since moving around. Having no hometown isn't a lack — it's a vantage point where, belonging nowhere, you can see everywhere.",
      tags: ['boundary', 'masan', 'nomad'], daysAgo: 0 },
    { id: 'th10', text: "The shock didn't come in that moment. Like a soldier on a battlefield, I felt nothing right there. The real shock came much later, back in ordinary life, when I realized I hadn't even felt sorrow at the time.",
      tags: ['malaria', 'png', 'commonsense'], daysAgo: 0 },
    { id: 'th11', text: "My first overseas experience is remembered not through a person, but through two dogs. Important memories always sit in the place you least expect.",
      tags: ['ireland', 'nomad'], daysAgo: 0 },
    { id: 'th12', text: "That evening in Prague, after my bag was stolen and I couldn't get help from anyone, a can of Budweiser I drank in the park tasted strangely good. Even in the hardest moment, the body finds comfort somewhere small, without fail.",
      tags: ['prague', 'stranger', 'survival'], daysAgo: 0 },
    { id: 'th13', text: "Finding a product with a thousandfold margin didn't make it a business. What my first failed venture taught me: the value people want and the value I want to show are two different things.",
      tags: ['salt', 'trade'], daysAgo: 0 },
    { id: 'th14', text: "In the threadbare winter after the theft, I ate the cheapest wine and a kebab wrapped in a blanket. A luxury I couldn't have justified back home became a small everyday happiness in the European cold.",
      tags: ['prague', 'vienna'], daysAgo: 0 },
    { id: 'th15', text: "The same scar of war landed as strangeness in Croatia and as sadness in Cambodia. Beauty already rebuilt versus a poverty still present — that difference is what split the feeling.",
      tags: ['croatia', 'cambodia'], daysAgo: 0 },
  ],

  openQuestions: [
    { node: 'ireland', q: 'Your first trip abroad in middle school — passing through England, France, and Hong Kong before settling in Dublin — how was that trip planned?' },
    { node: 'trade', q: 'During the time you were learning trade, besides salt, what other unexpected items were you chasing?' },
    { node: 'chain', q: 'Was there a moment fixing bicycles that made you especially proud?' },
    { node: 'subline', q: 'While subtitling, was there an expression that was especially hard to translate?' },
    { node: 'cambodia', q: 'Could you tell me more about the temple sites you saw in Cambodia, and how you ended up crossing paths with those American tourists?' },
    { node: 'croatia', q: 'Besides Croatia, are there other Eastern European countries from that era that stayed with you?' },
  ],

  combos: [
    { ids: ['pm', 'hands', 'bike'], title: 'From a Part, to a Maker',
      story: "Working as a part inside a massive car project, I carried a quiet regret — that I had never made anything from start to finish with my own hands. At thirty, I left a stable project-manager position and went to Tokyo to design bicycle frames myself; that was my answer to that regret. As I began understanding the world through my fingertips, I finally became a maker instead of a part.",
      weights: { pm: 0.8, hands: 1.15, bike: 1.35 } },
    { ids: ['pakistan', 'islam', 'adapt'], title: 'Fourteen, and My Values Shook',
      story: "Arriving in Islamabad at fourteen, following my father, I saw for the first time how completely religion could shape an entire society's way of life. In front of that scene — everyone stopping work to pray as day broke — my values shook to their core. But even amid that shaking, people adapt in the end, and I learned, in my own body, at that age, that the countless thoughts blooming out of that adaptation reshape the very way you live.",
      weights: { pakistan: 1.35, islam: 1.05, adapt: 1.15 } },
    { ids: ['png', 'malaria', 'commonsense'], title: 'Common Sense, Undone Under Darkness and Stars',
      story: "Beside the mill in Port Moresby, life and death were close together. When a coworker asked me to lend him money for his child's malaria medicine, I didn't lend it, and the child passed away. I felt nothing in that moment — like a soldier on a battlefield. The real shock came only after I returned to Korea: the belated realization that I hadn't even felt sorrow back then. That awareness redrew the boundaries of everything I'd believed was common sense.",
      weights: { png: 1.15, malaria: 1.35, commonsense: 1.05 } },
    { ids: ['boundary', 'masan', 'nomad'], title: 'A Person With No Hometown',
      story: "I was born in Masan, but I've never lived there for a single day — it was simply that Jinhae had no maternity hospital. From that point on, I was someone who never fully belonged anywhere. I've spent my whole life since crossing borders. Having no hometown isn't a lack; it's a place that can be both inside and outside, anywhere. Border-dweller — the one word that best describes me.",
      weights: { boundary: 1.4, masan: 1.0, nomad: 0.9 } },
    { ids: ['salt', 'pakistan', 'trade'], title: 'A Thousandfold Margin, and a Failure',
      story: "If it weren't for my connection to Pakistan, I'd never have thought to sell Himalayan rock salt — I had a hunch I could approach that country a bit better than most. That was during the time I was learning trade most passionately. A foot-soak product made from Himalayan pink salt that I found in a Japan market survey had a margin of nearly a thousandfold. But margin alone doesn't make a business — I learned that from the failure of my first venture.",
      weights: { salt: 1.35, pakistan: 0.9, trade: 1.05 } },
    { ids: ['prague', 'stranger', 'survival'], title: 'The Stolen Bag, and a Can of Beer',
      story: "When my suitcase was stolen at Prague's central station, no one in that crowded station helped me. That was the first time I understood the feeling of being unable to get help from anyone — that's what it means to live as an outsider. A can of Budweiser I drank sitting on a park bench, dragging my remaining heavy luggage, tasted strangely good in that hard moment. Surviving meant continuing to move even after the plan had collapsed — and sometimes, finding comfort in something small.",
      weights: { prague: 1.3, stranger: 0.95, survival: 1.05 } },
    { ids: ['ireland', 'pakistan', 'nomad'], title: 'Two Dogs and Shaken Values — My First Two Countries',
      story: "In my second year of middle school I went abroad for the first time and lived a month in Dublin. Barely a year or two later, I was living in Islamabad, following my father. Dublin's peaceful hillside where two dogs ran free, and Islamabad's unfamiliar afternoons where my values were shaken — these two, side by side, were my first overseas experiences. From then on, I was no longer someone who stayed in one place, but someone who moved.",
      weights: { ireland: 1.0, pakistan: 1.25, nomad: 1.1 } },
    { ids: ['teaching', 'multiling', 'bridge'], title: 'On the Bridge, Teaching How to Build One',
      story: "Korean, English, Chinese, Japanese — the four languages feel almost like four different personalities. Teaching Korean now at Hangzhou Normal University isn't simply passing on grammar. It's building a bridge between language and language, culture and culture. Someone who has lived his whole life on that bridge is now teaching others how to build one of their own.",
      weights: { teaching: 1.2, multiling: 1.0, bridge: 1.15 } },
  ],
};

if (typeof window !== 'undefined') window.DATA_EN = DATA_EN;
