/* =========================================================================
   Paul Bhang — Thought Constellation : DATA (single source of truth)
   -------------------------------------------------------------------------
   이 파일 하나만 고치면 사이트가 자랍니다. HTML/엔진은 건드릴 필요 없음.

   node.type:
     'core'        — 직접적인 나 (스킬/역할)
     'place'       — 나를 바꾼 장소 (지리적 기억)
     'associative' — 유사어·관심어 (사람들이 끌릴 인접 개념)
     'wildcard'    — 엉뚱해 보이지만 이야기를 숨긴 단어

   node.status:
     'told'  — Paul이 실제 이야기를 들려줘서 채워진 것
     'seed'  — 이력서 사실 기반으로 Claude가 초안 잡은 것
     'ask'   — 아직 Paul에게 물어보는 중 (진짜 이야기가 비어 있음)

   node.story  — 1인칭 스토리텔링 (이력서 나열 금지)
   node.links  — 성좌에서 이어질 관련 노드 id들
   ========================================================================= */

const DATA = {
  profile: {
    name: 'Paul Bhang',
    hangul: '방상훈',
    tagline: '15 years · 5 continents · 4 languages',
    places: 'HANGZHOU · SEOUL',
    hero1: '단어를 고르면,',
    hero2: '내가 보입니다.',
    heroSub: '머릿속을 떠다니는 단어들입니다. <b>두세 개를 골라 연결해 보세요</b> — 그 조합이 지나온 실제 이야기와 최근의 생각이 나타납니다. 어떤 단어는 나와 멀어 보여도, 클릭하면 이야기가 있습니다.',
    faces: 'LINGUIST · TRADER · MAKER · EDUCATOR · STORYTELLER · EXPLORER',
    email: 'bikeryhz@hotmail.com',
    location: 'Hangzhou, China · Incheon, Korea',
  },

  nodes: [
    /* ---------------- CORE : 직접적인 나 ---------------- */
    { id: 'interp', label: '통역·번역', type: 'core', status: 'seed',
      story: '말과 말 사이에 서는 일을 오래 했다. 한국어와 영어, 때로는 중국어 사이에서. 통역은 단어를 옮기는 게 아니라 두 사람이 서로를 믿게 만드는 일이라는 걸, 협상 테이블에서 배웠다.',
      links: ['multiling', 'bridge', 'vienna', 'shanghai'] },
    { id: 'multiling', label: '다국어', type: 'core', status: 'seed',
      story: '한국어는 모국어, 영어는 몸에 밴 언어, 중국어와 일본어는 살면서 주운 언어다. 네 개의 언어는 네 개의 인격에 가깝다. 언어를 바꾸면 생각의 결도 바뀐다.',
      links: ['interp', 'teaching', 'boundary'] },
    { id: 'sales', label: 'B2B 영업', type: 'core', status: 'seed',
      story: '소금부터 목재, 매장 집기, 자동차 부품까지 팔았다. 파는 물건은 계속 바뀌었지만 본질은 늘 같았다 — 상대가 무엇을 진짜로 원하는지 알아내는 일.',
      links: ['salt', 'timber', 'shanghai', 'trade'] },
    { id: 'pm', label: '프로젝트 관리', type: 'core', status: 'told',
      story: '베이징현대 프로젝트를 관리할 때 깨달았다. 기술 문제의 절반은 사실 문화 문제였다는 걸. 중재할 수 있는 사람이 프로젝트를 살린다. 하지만 거대한 조직의 한 부품으로 일하면서, 무언가를 처음부터 끝까지 내 손으로 만들어본 적이 없다는 아쉬움도 함께 자랐다.',
      links: ['shanghai', 'interp', 'hands', 'boundary'] },
    { id: 'subtitle', label: '영상·자막', type: 'core', status: 'seed',
      story: '6년간 한국어와 영어 사이의 자막을 만들었다. 번역은 언어의 문제가 아니라 타이밍과 리듬, 그리고 화면에 담기지 않는 함축의 문제였다. 한 줄에 담을 수 있는 건 생각보다 적다.',
      links: ['subline', 'interp', 'hangzhou'] },
    { id: 'bike', label: '자전거', type: 'core', status: 'told',
      story: '서른둘에 도쿄의 자전거 학교에 들어갔다. 프레임을 직접 설계하고, 내가 생각한 그대로 만들어냈다. 자전거는 나에게 자유의 상징이었다 — 어디로든 갈 수 있고, 새로운 것에 도전한다는 것. 그때 내 이상과 가장 잘 맞닿아 있던 물건. 남들이 경력을 쌓을 나이에, 나는 바퀴를 조립하며 처음으로 온전히 내 것을 만들었다.',
      links: ['tokyo', 'hands', 'freedom', 'chain'] },
    { id: 'logi', label: '물류', type: 'core', status: 'seed',
      story: '항공·해상 화물을 다루며 100개가 넘는 파트너사와 일했다. 물류는 신뢰가 곧 인프라인 세계다. 한 번의 실수가 지구 반대편의 누군가를 멈춰 세운다.',
      links: ['vienna', 'trade', 'survival'] },
    { id: 'teaching', label: '언어 교육', type: 'core', status: 'seed',
      story: '지금은 항저우사범대에서 한국어를 가르친다. 언어를 가르친다는 건 문법이 아니라 문화로 들어가는 문을 열어주는 일이다. 소프트파워는 교실에서 시작된다.',
      links: ['multiling', 'hangzhou', 'bridge'] },

    /* ---------------- PLACE : 나를 바꾼 장소 ---------------- */
    { id: 'pakistan', label: '파키스탄', type: 'place', era: '1997–1998', status: 'told',
      story: '아버지가 해군 장교로 파키스탄에 파견되면서, 열네 살의 나는 이슬라마바드에서 살게 됐다. 처음 마주한 충격은 이슬람이라는 종교가 사람들의 삶을 통째로 빚어내는 방식이었다. 가치관이 송두리째 흔들릴 만큼 거대한 변화 앞에서도 사람은 결국 그 안에서 적응한다는 것 — 그리고 그 적응 속에서 피어난 수많은 생각이 삶의 방식 자체를 바꿔놓는다는 것을, 그 나이에 처음 몸으로 알았다.',
      links: ['stranger', 'boundary', 'adapt', 'islam'] },
    { id: 'png', label: '파푸아뉴기니', type: 'place', era: '2009–2010', status: 'told', fresh: true,
      story: '포트모르즈비에서 마주한 삶은 파키스탄보다 더 극단적이었다. 목재 공장 부지 안, 한국에서 기계를 실어온 무역 컨테이너를 개조한 집에서 살았다. 밤이 되면 전기가 끊기고 공장 불도 꺼져, 아주 길고 깜깜한 밤이 이어졌다. 나무 부스러기를 모아 불을 피우고, 그때는 꽤 비쌌던 맥주를 한두 병 마시며 유난히 밝은 별들을 올려다보는 게 그곳의 하루였다. 일터 곁에서 죽음은 멀지 않았고, 말라리아는 너무 흔했다. 내가 상식이라 믿어온 것들이 실은 내가 자란 한 세계의 규칙일 뿐이었다는 걸, 그 어둠과 별 아래에서 알았다.',
      links: ['timber', 'survival', 'stranger', 'commonsense'] },
    { id: 'vienna', label: '비엔나', type: 'place', era: '2005–2007', status: 'seed',
      story: '스물몇 살에 비엔나 공항의 지사를 혼자 세웠다. 낯선 도시에서 회사 하나를 처음부터 만드는 일. 유럽의 한복판에서 나는 이방인이었고, 그게 오히려 무기가 됐다.',
      links: ['logi', 'stranger', 'boundary', 'prague'] },
    { id: 'prague', label: '프라하', type: 'place', era: '2005–2007', status: 'told', fresh: true,
      story: '비엔나로 향하던 길, 체코 프라하의 중앙역에서였다. 한국에 전화를 거는데 옆의 한 남자가 계속 나를 툭툭 치며 디지털카메라 같은 걸 팔려고 했다. 말이 안 통해 손짓으로 가라고 했다. 몇 번을 그러고 통화를 끝냈을 때, 여행가방 하나가 사라져 있었다 — 패거리였다. 역은 사람으로 가득했지만 아무도 도와주지 않았고, 몇 바퀴를 뛰어다녀도 못 찾았다. 경찰서에 갔지만 그땐 CCTV 같은 것도 없었다. 아무에게도 도움받을 수 없다는 감각을 그때 처음 알았다. 무거운 남은 짐을 끌고 역 옆 공원에 주저앉아, 근처 마트에서 산 오리지널 버드와이저 — 그땐 체코와 슬로바키아에서만 마실 수 있던 — 한 캔을 땄다. 그 힘들었던 순간에, 이상하리만치 맛있었다.',
      links: ['vienna', 'stranger', 'survival'] },
    { id: 'tokyo', label: '도쿄', type: 'place', era: '2014–2016', status: 'told', fresh: true,
      story: '도쿄로 가기로 한 건 어느 극적인 한순간이 아니었다. 자동차 회사에서 프로젝트 매니저로 일하던 그 직장은 사실 아주 좋은 직장이었다 — 월급도 나쁘지 않았고 대우도 좋았다. 그런데 삶이 점점 무료해졌다. 열정이 느껴지지 않는 하루하루가 쌓였다. 서른이 됐을 때, 지금 크게 한 번 바꾸지 않으면 너무 늦어버릴 것 같다는 생각이 자꾸 들었다. 그렇게 안정을 접고 도쿄의 학생으로 돌아갔다.',
      links: ['bike', 'hands', 'pm', 'drift'] },
    { id: 'shanghai', label: '상하이', type: 'place', era: '2010–2013', status: 'seed',
      story: '매장 집기를 유럽에 수출하다가, 자동차 안전부품 회사의 프로그램 매니저가 됐다. 한국과 중국 비즈니스 문화 사이의 통역자 — 그게 내 진짜 직함이었다.',
      links: ['sales', 'pm', 'interp'] },
    { id: 'hangzhou', label: '항저우', era: '2017–현재', type: 'place', status: 'seed',
      story: '게스트하우스를 열고, 자막을 만들고, 지금은 대학에서 가르친다. 오래 떠돌던 사람이 처음으로 한곳에 뿌리를 내린 도시. 아직 쓰이는 중인 챕터.',
      links: ['teaching', 'subtitle', 'guesthouse'] },
    { id: 'ireland', label: '아일랜드', type: 'place', era: '1996 무렵', status: 'told', fresh: true,
      story: '중학교 2학년, 난생처음 해외로 나갔다. 영국, 프랑스, 홍콩을 며칠씩 스치듯 지나 더블린에 도착해 한 달을 살았다. 수도인데도 집 바로 뒤로 언덕길 산책로가 있었고, 그 이층집엔 몸집이 큰 개 두 마리가 있었다. 소파에 앉아 있다가 아무 때나 다가와 놀고, 산책 시간이면 따라나서던 그 모습이 지금도 가장 선명하다. 첫 해외 경험이 사람이 아니라 개 두 마리로 기억된다는 게, 나쁘지 않다.',
      links: ['pakistan', 'nomad', 'stranger'] },
    { id: 'jinhae', label: '진해', type: 'place', era: '1983 · 2003–2005', status: 'told',
      story: '삶이 시작된 자리이자, 훗날 해군에서 군복무로 돌아온 곳. 아버지가 해군이라 우리 가족은 진해에 있었다. 하지만 정작 나는 진해에서 태어나지 못했다 — 그때 진해엔 산부인과가 없어, 어머니는 마산으로 건너가 나를 낳았다. 시작부터 나는 어느 한 곳에도 온전히 속하지 않는 사람이었다.',
      links: ['boundary', 'masan', 'stranger'] },
    { id: 'masan', label: '마산', type: 'place', era: '1983', status: 'told',
      story: '서류상 내 고향. 하지만 하루도 살아본 적이 없다. 진해에 산부인과가 없어 어머니가 잠시 건너와 나를 낳은 곳일 뿐. 태어난 자리와 살아갈 자리가 처음부터 어긋나 있었다 — 어쩌면 그게 내 인생의 첫 은유였다.',
      links: ['jinhae', 'boundary', 'nomad'] },

    /* ---------------- ASSOCIATIVE : 유사어·관심어 ---------------- */
    { id: 'nomad', label: '노마드', type: 'associative', status: 'seed',
      story: '한 도시에 오래 머문 적이 없다. 서울, 비엔나, 포트모르즈비, 상하이, 도쿄, 항저우. 떠도는 건 도망이 아니라 수집이었다 — 매번 다른 방식의 삶을 주워 담았다.',
      links: ['drift', 'stranger', 'survival'] },
    { id: 'boundary', label: '경계인', type: 'associative', status: 'told',
      story: '누가 고향을 물으면 나는 고향이 없는 사람이라고 답하곤 한다. 태어난 마산엔 살아본 적 없고, 그 뒤로 평생 여러 나라를 옮겨 다녔으니까. 어디서도 완전한 안이 아니었고 완전한 밖도 아니었다 — 한국인이면서 중국에서 가르치고, 세일즈맨이면서 정비공이었다. 경계에 선 사람만 볼 수 있는 것들이 있다. 나를 가장 잘 설명하는 한 단어를 고르라면, 아마 이것이다.',
      links: ['stranger', 'bridge', 'nomad', 'masan'] },
    { id: 'stranger', label: '이방인', type: 'associative', status: 'seed',
      story: '낯선 사람으로 사는 데 익숙하다. 이방인은 아무것도 당연하게 여기지 않기 때문에 더 많이 본다. 불편함은 오래전에 나의 기본값이 됐다.',
      links: ['boundary', 'nomad', 'pakistan'] },
    { id: 'hands', label: '손끝', type: 'associative', status: 'told',
      story: '큰 회사에서 나는 늘 거대한 기계의 한 부품이었다. 무역을 하고 자동차 회사에서 프로젝트를 관리하면서도, 처음부터 끝까지 내 손으로 만들어낸 게 없다는 아쉬움이 쌓였다. 나이가 들면 무기력한 사람이 되는 건 아닐까. 그래서 손끝으로 직접 만들기 시작했다 — 머리로만 살던 사람이, 물건을, 그리고 세상을 다르게 신뢰하게 됐다.',
      links: ['bike', 'pm', 'tokyo'] },
    { id: 'survival', label: '생존', type: 'associative', status: 'seed',
      story: '인프라가 없는 곳, 규칙이 다른 곳에서 사업을 굴려봤다. 살아남는다는 건 계획대로 되는 게 아니라, 계획이 무너진 뒤에도 계속 움직이는 능력이었다.',
      links: ['png', 'nomad', 'trade'] },
    { id: 'bridge', label: '다리', type: 'associative', status: 'seed',
      story: '평생 두 세계 사이에 다리를 놓는 일을 했다. 언어와 언어, 문화와 문화, 사는 쪽과 파는 쪽. 다리는 양쪽 어디에도 온전히 속하지 않아야 제 역할을 한다.',
      links: ['interp', 'boundary', 'teaching'] },
    { id: 'drift', label: '표류', type: 'associative', status: 'seed',
      story: '직선으로 산 적이 없다. 물류에서 창업으로, 목재에서 자전거로, 궤도는 늘 휘어졌다. 표류처럼 보였지만 지나고 보니 하나의 지도였다.',
      links: ['nomad', 'tokyo', 'drift'] },
    { id: 'adapt', label: '적응', type: 'associative', status: 'told',
      story: '가치관이 흔들릴 만큼 거대한 변화 앞에서도 사람은 그 안에서 적응한다. 열네 살의 파키스탄에서 배운 것. 적응은 굴복이 아니라, 낡은 세계가 무너진 자리에서 새로운 생각이 피어나는 과정이었다.',
      links: ['pakistan', 'boundary', 'survival'] },
    { id: 'commonsense', label: '상식', type: 'associative', status: 'told',
      story: '내가 상식이라 부르던 것들은 대개 내가 자란 한 세계의 규칙일 뿐이었다. 파푸아뉴기니가 그 경계를 무너뜨린 뒤로, 나는 어떤 것도 당연하게 여기지 않는 사람이 됐다.',
      links: ['png', 'stranger', 'survival'] },
    { id: 'islam', label: '이슬람', type: 'associative', status: 'told',
      story: '한국과, 잠깐 여행했던 유럽 몇 나라를 빼면, 파키스탄은 내가 본 가장 극단적으로 다른 삶의 형태였다. 낮이 되면 사람들이 하던 일을 모두 멈추고 기도를 올렸다. 종교가 무엇보다 앞서는 삶의 방식. 열네 살의 나는 그 앞에서 여러 감정이 뒤섞였다 — 낯섦과 함께, 세상이 내가 알던 것보다 훨씬 넓다는 어렴풋한 깨달음.',
      links: ['pakistan', 'stranger', 'adapt'] },
    { id: 'freedom', label: '자유', type: 'associative', status: 'told',
      story: '자전거가 나에게 자유의 상징이었던 것처럼, 나는 늘 자유로움과 새로운 것에 대한 도전에 끌렸다. 한곳에 매이지 않는 것, 내 손으로 방향을 정하는 것. 그게 평생 나를 움직여온 이상이었다.',
      links: ['bike', 'nomad', 'drift'] },

    /* ---------------- WILDCARD : 엉뚱하지만 이야기가 있는 ---------------- */
    { id: 'salt', label: '소금', type: 'wildcard', status: 'told', fresh: true,
      story: '히말라야 암염을 팔게 된 건 파키스탄과의 인연 때문이었다 — 그 나라라면 남들보다 조금 더 잘 다가갈 수 있다는 감이 있었다. 그때는 무역을 가장 열정적으로 배우던 시절이었다. 매일 새 아이템을 찾고, 원가와 물류비, 관세와 부가세를 하나하나 계산해 한국 판매가와 비교하며 마진율이 가장 높은 상품을 찾아다녔다. 그러다 일본 시장조사에서 히말라야 핑크솔트로 만든 족욕제를 봤다 — 계산해보니 마진율이 거의 천 배, 그때까지 계산한 모든 아이템 중 최고였다. 하지만 마진율만으론 사업이 되지 않았다. 수요 예측은 서툴렀고, 첫 창업이었다. 그 실패에서 배운 건 하나였다 — 사람들이 원하는 가치와 내가 보여주고 싶은 가치는 다르다는 것.',
      links: ['trade', 'pakistan', 'sales'] },
    { id: 'timber', label: '목재', type: 'wildcard', status: 'seed',
      story: '파푸아뉴기니의 제재소에서 목재를 다뤘다. 나무를 베고, 켜고, 팔았다. 자연에서 바로 나온 원자재를 다루는 일은 도시의 비즈니스와 완전히 다른 감각을 요구했다.',
      links: ['png', 'sales', 'survival'] },
    { id: 'noni', label: '노니', type: 'wildcard', status: 'seed',
      story: 'PNG에서 투자할 아이템을 찾아 헤맬 때 목록에 있던 것 중 하나. 노니, 커피, 흑단, 고철, 심지어 태권도까지. 무엇이든 사업이 될 수 있는 곳에서 나는 가능성의 냄새를 맡는 법을 익혔다.',
      links: ['png', 'coffee', 'trade'] },
    { id: 'coffee', label: '커피', type: 'wildcard', status: 'seed',
      story: 'PNG의 고원지대는 세계적인 커피 산지다. 투자 조사 목록에 커피가 있었다. 결국 하진 않았지만, 그때 배운 시장 읽는 눈은 남았다.',
      links: ['noni', 'png'] },
    { id: 'ebony', label: '흑단', type: 'wildcard', status: 'seed',
      story: '검고 단단한 나무, 흑단. PNG에서 이걸 투자 아이템으로 검토했다. 희귀한 것에는 늘 이야기와 위험이 함께 붙어 있었다.',
      links: ['noni', 'timber', 'png'] },
    { id: 'taekwondo', label: '태권도', type: 'wildcard', status: 'seed',
      story: '믿기 어렵겠지만, PNG 투자 조사 목록에 태권도가 있었다. 한국의 것을 남태평양에 심는 상상. 결국 다른 형태로 — 언어와 문화를 가르치는 일로 — 이뤄진 셈이다.',
      links: ['png', 'teaching', 'bridge'] },
    { id: 'scrap', label: '고철', type: 'wildcard', status: 'seed',
      story: '고철도 사업 아이템이었다. 남들이 쓰레기라 부르는 것에서 가치를 보는 일. 버려진 것에서 다시 쓸모를 찾는 눈은, 사람에게도 똑같이 쓰인다.',
      links: ['png', 'survival', 'trade'] },
    { id: 'subline', label: '자막 한 줄', type: 'wildcard', status: 'seed',
      story: '자막 한 줄에 담을 수 있는 글자 수는 정해져 있다. 그 제약 안에서 원문의 뜻과 감정을 모두 살려야 했다. 제약은 창의의 반대말이 아니라 그 조건이었다.',
      links: ['subtitle', 'interp'] },
    { id: 'chain', label: '체인', type: 'wildcard', status: 'seed',
      story: '자전거 체인은 기름과 먼지로 더러워지는 부품이지만, 그게 없으면 아무 데도 못 간다. 눈에 안 띄지만 모든 걸 움직이게 하는 것들 — 나는 늘 그런 것에 끌렸다.',
      links: ['bike', 'hands'] },
    { id: 'trade', label: '무역', type: 'wildcard', status: 'seed',
      story: '평생 무언가를 국경 너머로 옮겼다. 소금, 주스 원액, 목재, 매장 집기. 무역은 물건이 아니라 신뢰를 국경 너머로 옮기는 일이었다.',
      links: ['salt', 'sales', 'logi', 'boundary'] },
    { id: 'guesthouse', label: '게스트하우스', type: 'wildcard', status: 'seed',
      story: '항저우에서 게스트하우스를 열었다. 이벤트, 마케팅, 자전거 정비까지 혼자 다 했다. 멀티태스킹처럼 보였지만 사실은 비즈니스 전체를 한 몸으로 이해하는 훈련이었다.',
      links: ['hangzhou', 'hands', 'survival'] },
    { id: 'malaria', label: '말라리아', type: 'wildcard', status: 'told', fresh: true,
      story: '함께 일하던 동료가 아이의 말라리아 약값을 빌려달라며 찾아온 적이 있다. 나는 빌려주지 않았고, 얼마 뒤 그 아이는 세상을 떠났다. 이상한 건 그 순간이 아니었다. 전장의 병사가 그 자리에선 죽음을 실감하지 못하듯, 나 역시 그때는 아무것도 느끼지 못했다. 진짜 충격은 한참 뒤, 그곳 생활을 마치고 한국의 일상으로 돌아왔을 때 찾아왔다 — 한 아이의 죽음 앞에서 나는 그때 슬픔도 고통도 느끼지 못했었구나, 라는 뒤늦은 깨달음. 그 사실이 죽음 자체보다 오래 나를 따라다녔다.',
      links: ['png', 'commonsense', 'survival'] },
  ],

  /* 시간이 흐르는 생각들 — 특정 노드에 걸려 있음 */
  thoughts: [
    { id: 'th1', text: '15년간 5개 대륙에서 일하며 배운 것: 언어와 문화는 기술 스펙만큼 중요하다. 계약의 절반은 신뢰와 이해에서 나온다.',
      tags: ['multiling', 'boundary', 'bridge'], daysAgo: 0 },
    { id: 'th2', text: '자전거를 만지며 느낀 것 — 손으로 고칠 줄 아는 사람은 세상을 다르게 신뢰한다. 물리적 이해가 사고의 바닥을 만든다.',
      tags: ['bike', 'hands'], daysAgo: 1 },
    { id: 'th3', text: '소금과 주스 원액을 동시에 팔던 시절: 작은 사업이라도 전체 사이클을 이해하면, 어떤 산업이든 다시 읽을 수 있게 된다.',
      tags: ['salt', 'trade', 'sales'], daysAgo: 2 },
    { id: 'th4', text: '이방인으로 사는 데 익숙해지면, 아무것도 당연하지 않아서 더 많이 보게 된다. 불편함이 오래전에 기본값이 됐다.',
      tags: ['stranger', 'boundary', 'nomad'], daysAgo: 3 },
    { id: 'th5', text: '표류처럼 보였던 궤도가 지나고 보니 하나의 지도였다. 직선이 아니어도 방향은 있었다.',
      tags: ['drift', 'nomad'], daysAgo: 4 },
    { id: 'th6', text: '가장 낯선 곳에서 생각이 가장 크게 바뀌었다. 파키스탄과 파푸아뉴기니 — 편안했던 적 없는 곳들이 나를 만들었다.',
      tags: ['pakistan', 'png', 'stranger'], daysAgo: 5 },
    { id: 'th7', text: '파키스탄에서는 거대한 변화 속에서도 사람이 적응한다는 걸 배웠고, 파푸아뉴기니에서는 내 상식이 얼마나 좁은 세계의 규칙이었는지를 배웠다. 낯섦은 늘 스승이었다.',
      tags: ['adapt', 'commonsense', 'pakistan', 'png'], daysAgo: 0 },
    { id: 'th8', text: '거대한 조직의 부품으로 일할수록, 무언가를 처음부터 끝까지 내 손으로 만들고 싶었다. 자전거 프레임을 직접 설계하며 그 갈증을 풀었다 — 자유란 결국 내 손으로 방향을 정하는 일이었다.',
      tags: ['pm', 'bike', 'hands', 'freedom'], daysAgo: 0 },
    { id: 'th9', text: '태어난 도시에 하루도 살지 않았고, 그 뒤로 평생 옮겨 다녔다. 고향이 없다는 건 결핍이 아니라, 어디에도 속하지 않아 어디든 볼 수 있는 자리였다.',
      tags: ['boundary', 'masan', 'nomad'], daysAgo: 0 },
    { id: 'th10', text: '충격은 그 순간에 오지 않았다. 전장의 병사처럼, 그 자리에선 아무것도 느끼지 못했다. 진짜 충격은 한참 뒤 일상으로 돌아와, 그때 슬픔조차 느끼지 못했었다는 걸 깨달았을 때 왔다.',
      tags: ['malaria', 'png', 'commonsense'], daysAgo: 0 },
    { id: 'th11', text: '첫 해외 경험이 사람이 아니라 개 두 마리로 남아 있다. 중요한 기억은 늘 예상 못 한 자리에 앉아 있다.',
      tags: ['ireland', 'nomad'], daysAgo: 0 },
    { id: 'th12', text: '가방을 도둑맞고 아무 도움도 받을 수 없던 프라하의 그 저녁, 공원에서 마신 버드와이저 한 캔이 이상하리만치 맛있었다. 가장 힘든 순간에도 몸은 작은 것에서 기어이 위안을 찾는다.',
      tags: ['prague', 'stranger', 'survival'], daysAgo: 0 },
    { id: 'th13', text: '마진율 천 배짜리 상품을 찾아냈다고 사업이 되는 게 아니었다. 첫 창업의 실패에서 배운 것: 사람들이 원하는 가치와 내가 보여주고 싶은 가치는 다르다.',
      tags: ['salt', 'trade'], daysAgo: 0 },
  ],

  /* 넛지 루프 — Claude가 아직 Paul에게 묻고 싶은 것들.
     대화하며 하나씩 채우고, 채워지면 여기서 지운다.
     일부러 커리어 순서를 벗어난 가벼운/랜덤한 질문도 섞는다. */
  openQuestions: [
    { node: 'ireland', q: '중2 첫 해외여행 — 영국·프랑스·홍콩을 스치고 더블린에 정착하기까지, 그 여행은 어떻게 계획됐나요?' },
    { node: 'trade', q: '무역을 배우던 그 시절, 소금 말고 또 어떤 엉뚱한 아이템들을 찾아다녔나요?' },
    { node: 'chain', q: '자전거를 고치면서 가장 뿌듯했던 순간이 있다면?' },
    { node: 'subline', q: '자막 작업하면서 가장 옮기기 어려웠던 표현이 있었나요?' },
    { node: 'vienna', q: '비엔나에서 지내며 가장 사소하지만 행복했던 일상은 뭐였나요?' },
  ],

  /* 큐레이션된 조합 스토리 — 성좌에서 정확히 이 단어 조합을 골랐을 때,
     여러 노드를 하나의 흐르는 1인칭 이야기로 엮어 보여준다.
     weights: 이 이야기 안에서 각 단어가 가진 중요도(0.6~1.5) — 성좌에서 단어 크기에 반영됨.
     ids 순서는 무관 — 선택된 단어 집합과 정확히 일치할 때만 매칭된다. */
  combos: [
    { ids: ['pm', 'hands', 'bike'], title: '부품에서, 만드는 사람으로',
      story: '거대한 자동차 프로젝트의 부품으로 일하면서, 나는 처음부터 끝까지 내 손으로 무언가를 만들어본 적이 없다는 아쉬움을 안고 있었다. 서른, 안정된 프로젝트 매니저 자리를 접고 도쿄로 가 자전거 프레임을 직접 설계하기 시작한 건 그 아쉬움에 대한 답이었다. 손끝으로 세상을 이해하기 시작하면서, 나는 비로소 부품이 아니라 만드는 사람이 됐다.',
      weights: { pm: 0.8, hands: 1.15, bike: 1.35 } },
    { ids: ['pakistan', 'islam', 'adapt'], title: '가치관이 흔들리던 열네 살',
      story: '아버지를 따라 열네 살에 도착한 이슬라마바드에서, 나는 처음으로 종교가 한 사회의 삶 전체를 빚어내는 모습을 봤다. 낮이 되면 모두가 일을 멈추고 기도하는 그 풍경 앞에서 가치관이 통째로 흔들렸다. 하지만 그 흔들림 속에서도 사람은 결국 적응한다는 것 — 그리고 그 적응의 과정에서 피어나는 수많은 생각이 삶의 방식 자체를 바꿔놓는다는 것을, 나는 그 나이에 몸으로 배웠다.',
      weights: { pakistan: 1.35, islam: 1.05, adapt: 1.15 } },
    { ids: ['png', 'malaria', 'commonsense'], title: '어둠과 별 아래에서 무너진 상식',
      story: '포트모르즈비의 공장 옆에서 삶과 죽음은 가까웠다. 한 동료가 아이의 말라리아 약값을 빌려달라 했을 때 나는 빌려주지 않았고, 그 아이는 세상을 떠났다. 그 순간엔 아무것도 느끼지 못했다 — 전장의 병사처럼. 진짜 충격은 한국으로 돌아와서야 왔다: 그때 나는 슬픔조차 느끼지 못했었다는 뒤늦은 깨달음. 그 자각이 내가 상식이라 믿어온 것들의 경계를 다시 그렸다.',
      weights: { png: 1.15, malaria: 1.35, commonsense: 1.05 } },
    { ids: ['boundary', 'masan', 'nomad'], title: '고향 없는 사람',
      story: '태어난 곳은 마산이지만 하루도 살아본 적이 없다. 진해에 산부인과가 없어서였을 뿐인데, 그때부터 나는 어디에도 완전히 속하지 않는 사람이었다. 그 뒤로 평생 국경을 옮겨 다녔다. 고향이 없다는 건 결핍이 아니라, 어디서든 안이자 밖일 수 있는 자리였다 — 경계인, 나를 가장 잘 설명하는 한 단어.',
      weights: { boundary: 1.4, masan: 1.0, nomad: 0.9 } },
    { ids: ['salt', 'pakistan', 'trade'], title: '마진율 천 배의 실패',
      story: '파키스탄과의 인연이 없었다면 히말라야 암염을 팔 생각도 못 했을 것이다. 그 나라라면 남들보다 조금 더 잘 다가갈 수 있다는 감이 있었다. 무역을 가장 열정적으로 배우던 시절, 일본에서 본 히말라야 핑크솔트 족욕제의 마진율은 거의 천 배였다. 하지만 마진율만으론 사업이 되지 않는다는 걸, 그 첫 창업의 실패에서 배웠다.',
      weights: { salt: 1.35, pakistan: 0.9, trade: 1.05 } },
    { ids: ['prague', 'stranger', 'survival'], title: '도둑맞은 가방, 그리고 맥주 한 캔',
      story: '체코 프라하의 중앙역에서 여행가방을 도둑맞았을 때, 사람으로 가득한 역에서 아무도 나를 돕지 않았다. 아무에게도 도움받을 수 없다는 감각을 그때 처음 알았다 — 이방인으로 산다는 게 그런 것이었다. 무거운 남은 짐을 끌고 주저앉은 공원 벤치에서 마신 버드와이저 한 캔이, 그 힘든 순간에 이상하리만치 맛있었다. 살아남는다는 건 계획이 무너진 뒤에도 계속 움직이는 것, 그리고 가끔은 작은 것에서 위안을 찾는 것이었다.',
      weights: { prague: 1.3, stranger: 0.95, survival: 1.05 } },
    { ids: ['ireland', 'pakistan', 'nomad'], title: '개 두 마리와 흔들린 가치관, 나의 첫 두 나라',
      story: '중2 때 처음 해외로 나가 더블린에서 한 달을 살았다. 그리고 겨우 한두 해 뒤, 아버지를 따라 이슬라마바드에서 살게 됐다. 개 두 마리가 뛰놀던 더블린의 평화로운 언덕과, 가치관이 뒤흔들리던 이슬라마바드의 낯선 오후 — 이 둘이 나란히 나의 첫 해외 경험이었다. 그때부터 나는 한곳에 머무는 사람이 아니라 옮겨 다니는 사람이 되어 있었다.',
      weights: { ireland: 1.0, pakistan: 1.25, nomad: 1.1 } },
    { ids: ['teaching', 'multiling', 'bridge'], title: '다리 위에서, 다리 놓는 법을 가르치다',
      story: '한국어, 영어, 중국어, 일본어 — 네 개의 언어는 네 개의 인격에 가깝다. 지금 항저우사범대에서 한국어를 가르치는 건 단순히 문법을 전달하는 일이 아니다. 언어와 언어 사이, 문화와 문화 사이에 다리를 놓는 일이다. 평생 그 다리 위에서 살아온 사람이 이제는 다른 사람들에게 다리 놓는 법을 가르치고 있다.',
      weights: { teaching: 1.2, multiling: 1.0, bridge: 1.15 } },
  ],
};

if (typeof window !== 'undefined') window.DATA = DATA;
